16-Role-pages
r3399r/sirius pull request #20
Opened 2021-07-14 14:30 UTC by coolcold1898

2021-07-15 01:29 UTC, r3399r reviewed
透過在 `NewRecord` 裡增加 `index` 來避免同名的問題沒有很理想...
我發現
`index=0` 時對應 `Type` 
`index=1` 時對應 `Player`
`index=2` 時對應 `Role`
`index=3` 時對應 `Night`
那表示這個 `index` 是直接對應於各個 component，也表示我當時「傳 rolename 進 component」的想法顯然不是一個好 idea

我們讓 `NewRecord` 主要控制大步驟 (type, player, role, night, datime)，也就是我們最初的樣子
小步驟可以在各個 component 裡面做
例如在 `Role.tsx` 裡面加上
```
...
const [roleStep, setRoleStep] = useState<number>(0)
...
const onSubmitClick() => () => {
  ...
  setRoleStep(roleStep+1)
  ...
}
...
```
利用 `roleStep` 判斷哪些地方該顯示什麼
讓「分發角色」限制在 `Role.tsx` 裡面完成即可，且這次新增的內容的確也是一直都是處在這個步驟
等分發完成後再讓 `NewRecord` 進入下一個階段

改改看吧

2021-07-15 01:35 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +          {state.record.player?.map((v: PlayerProps, i: number) => {
`state.record.player` 的 type 已被定義於 `src/model/Record`
所以 不用在這邊臨時定義 `PlayerProps`，直接引用 第5行 import 的 `PlayerType` 即可

2021-07-15 13:39 UTC, r3399r commented on src/pages/newRecord/components/Night.tsx
> +  };
```
const onSubmitClick = () => {
    if (nightStep === 4) onClick();
    else setNightStep(nightStep + 1);
};
```
下面 47行 改成 `onClick={onSubmitClick}`

2021-07-15 13:48 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +  const [PresentRole, SetPresentRole] = useState<string>('');
`presentRole`, `setPresentRole`

2021-07-15 13:51 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +import { useDispatch } from 'react-redux';
4,5行可以合併，沒想到 fix 不會修這個

2021-07-15 13:58 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +  const onReturnClick = () => () => {
`const onReturnClick = () => {`

2021-07-15 13:58 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +        <Button type="text" className={style.btn} onClick={onReturnClick()}>
`onClick={onReturnClick}`

2021-07-15 14:00 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +                  [style.clicked]: state.record.player![i].role || undefined,
後面的 `|| undefined` 應該沒作用?

2021-07-15 16:55 UTC, r3399r commented on src/pages/newRecord/components/Night.tsx
> +import { Player as PlayerType } from 'src/model/Record';
`import { Player } from 'src/model/Record';`
下面出現 `PlayerType` 的地方都改成 `Player`

2021-07-15 16:57 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +import { Player as PlayerType } from 'src/model/Record';
`import { Player } from 'src/model/Record';`

2021-07-15 16:57 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +    for (let i = 0; i < 12; i++) if (state.record.player![i].role !== undefined) count++;
避免使用 `for` 迴圈

2021-07-15 17:30 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +      if (roleStep === 6) onClick();
建議改成只在最後一步時存 redux 就好
可以用原本的 `setPlayer` 存
準備一整串完整的 `Player[]` 再 `dispatch(setPlayer(xxx))`

2021-07-15 17:34 UTC, r3399r commented
1. 避免使用 for-loop
2. 善用 useState 存一些需要的狀態，看起來 step 非常重要
3. 最終存一次 redux 就好

2021-07-15 17:36 UTC, r3399r reviewed
1. 避免使用 for-loop
2. 善用 useState 存一些需要的狀態，看起來 step 非常重要
3. 最終存一次 redux 就好

2021-07-16 15:15 UTC, r3399r requested changes

2021-07-16 15:15 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +    if (roleStep === 6) onClick();
在 roleStep = 6 這裡 dispatch 就好
現在 onReturnClick 裡面會這麼複雜有一個原因就是因為 redux 已被改動, 所以為了存取正確在返回時也要去修正它
但其實可以不用修正, 返回時回到上一步後, 進行選擇時可以直接覆蓋錯誤的地方
在用 dispatch 存進 redux 時確認存的值是我們要的就可以了
另外，若這樣做, dispatch 可以直接用 setPlayer。setRole 就可以刪掉了

2021-07-16 15:15 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +const roleJudge = (roleName: any) => {
參考我在 issue 中留言提到的方法取代這邊

2021-07-20 17:21 UTC, r3399r reviewed
請修改

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +  const [numOrder, setNumOrder] = useState<Number[]>([]);
`Number` -> `number`

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +  const [whichIsClicked, setWhichIsClicked] = useState<Number[]>([]);
`Number` -> `number`

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +        </div>
102 和 104 夾著的 `div` 應可以拿掉

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +  const displayRoleJudge = (i: Number) => {
`Number` -> `number`

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +  const onRoleClick = (num: string, playerRole: string) => () => {
`playerRole` 這個參數不會用到可以拿掉

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +                key={i}
`key={i}` -> `key={v.id}`
由於 `key` 值不能重複，所以為了方便使用 index `i`，但是不得已才使用 index，如果 map 的每個 element 有 unique 的值，如 `v.id`，就可以取代 `i`

這個改完之後 106行的 `i` 應該就會變灰，表示沒有地方用到它了，就可以拿掉

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +      });
不需要排序，我們不依賴 array 中 element 的位置，array 的成員們都是同等的，所以我們有存代表排序的資訊 `id`
第一個位置不一定是第一個角色，id=1 的是第一個角色

我有注意到 `Night` 頁面在渲染時會直接按這個順序顯示按鈕，也許這邊排序是為了 `Night` 而鋪路，但是那個是 `Night` 的事情，給 `Night` 去做就好，這裡只管資料儲存正確，最重要的觀念是，array 的成員們是同等級的，沒有順序性

2021-07-20 17:21 UTC, r3399r commented on src/pages/newRecord/components/Role.tsx
> +        const name = state.record.player![Number(element) - 1].name;
由於 `state.record.player` 的 array 的成員們不需要有順序性，所以取值時不能依賴位置(雖然這邊並不會出錯)
改成從 id 找到對應的 name
`const name = _(state.record.player).find((v: Player) => v.id === id)!.name;`
最前面要 `import _ from 'lodash';`

lodash 這個 library 很好用，尤其是對 array、object、array of object 的資料處理，有很多很方便的函數

2021-07-20 17:29 UTC, r3399r reviewed
還有2點

2021-07-20 17:29 UTC, r3399r commented on src/services/RecordService.ts
> +  nightNull: string;
改成 `nightAction: string | null;` 和 `nightNull: string | null;`
然後下面的空字串改成 `null`

2021-07-20 17:29 UTC, r3399r commented on src/redux/recordSlice.ts
> +export const { setType, setPlayer, setRole } = recordSlice.actions;
這裡的 `setRole` 就不需要了

2021-07-20 17:31 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +  const [numOrder, setNumOrder] = useState<Number[]>([]);
done

2021-07-20 17:31 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +  const [whichIsClicked, setWhichIsClicked] = useState<Number[]>([]);
done

2021-07-20 17:32 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +        </div>
done

2021-07-20 17:32 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +  const displayRoleJudge = (i: Number) => {
done

2021-07-20 17:33 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +  const onRoleClick = (num: string, playerRole: string) => () => {
done

2021-07-20 17:33 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +                key={i}
done

2021-07-20 17:34 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +      });
done

2021-07-20 17:36 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +      });
done

2021-07-20 17:36 UTC, coolcold1898 commented on src/pages/newRecord/components/Role.tsx
> +        const name = state.record.player![Number(element) - 1].name;
done

2021-07-20 17:40 UTC, coolcold1898 commented on src/services/RecordService.ts
> +  nightNull: string;
done

2021-07-20 17:40 UTC, coolcold1898 commented on src/redux/recordSlice.ts
> +export const { setType, setPlayer, setRole } = recordSlice.actions;
done

2021-07-20 17:52 UTC, r3399r approved these changes
looks good to me

2021-07-20 17:53 UTC, merged